- 
  name: Deploy a 5G Core
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install Dependency
      apt:
        name: software-properties-common
        state: present

    - name: Add open5gs latest repository from PPA
      ansible.builtin.apt_repository:
        repo: 'ppa:open5gs/latest'

    - name: Again Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install Open5GS
      apt:
        name: open5gs
        state: present

    - name: Update AMF config
      replace:
        path: /etc/open5gs/amf.yaml
        after: 'amf:\n\s+sbi:\n\s+\-\s+addr\:'
        before: 'guami:'
        regexp: '(\-\s+addr\:\s)+127\.0\.0\.5'
        replace: '\g<1>{{ ansible_host }}'
        backup: yes


    - name: Update UPF config
      replace:
        path: /etc/open5gs/upf.yaml
        after: 'upf:\n\s+pfcp:\n\s+\-\s+addr\:'
        before: 'subnet:'
        regexp: '(\-\s+addr\:\s)+127\.0\.0\.7'
        replace: '\g<1>{{ ansible_host }}'
        backup: yes


    - name: Restart AMF Service
      systemd:
        name: open5gs-amfd
        state: restarted
        enabled: true

    - name: Restart UPF Service
      systemd:
        name: open5gs-upfd
        state: restarted
        enabled: true

    - name: NAT Port Forwarding
      shell: |
        sudo sysctl -w net.ipv4.ip_forward=1
        sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        sudo systemctl stop ufw
        sudo iptables -I FORWARD 1 -j ACCEPT

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install curl
      apt:
        name: curl
        state: present
    
    - name: curl package
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Clone code open5gs
      shell: |
        sudo rm -rf open5gs
        git clone https://github.com/open5gs/open5gs.git

    - name: Run Dashboard
      shell: |
        cd open5gs/webui
        npm ci --no-optional && npm run build
        npm run dev --host 0.0.0.0
